# site settings
title: Studio Next
subtitle: Mobile Apps
email: mert@studionext.co.uk
description: Building thoughtful mobile apps for mindful living. Meditation, journaling, and creative expression.
baseurl: ""
url:
author:

# social settings
github_url: https://github.com/mertnesvat/
instagram_url: https://www.instagram.com/mertmakesstuff/
youtube_url: https://www.youtube.com/@mnesvat/shorts
tiktok_url: https://www.tiktok.com/@mertbuilds

# build settings
markdown: kramdown

sass:
  style: compressed
